'use client';
import { useRef,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { gameFetch } from '@/lib/game-client';
import type { Catalog,RestaurantPool } from '@/lib/types';
export function RestaurantPools({catalog,apply,saved,disabled}: {catalog:Catalog;apply:(ids:string[])=>void;saved:(c:Catalog)=>void;disabled:boolean}) {
  const [selected,setSelected]=useState(''),[editing,setEditing]=useState<RestaurantPool|'new'|null>(null),[deleting,setDeleting]=useState<RestaurantPool|null>(null);
  const [name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const pendingEditor=useRef<RestaurantPool|'new'|null>(null);
  const attempt=useRef<Record<string,unknown>|null>(null),requestId=useRef(''),[retry,setRetry]=useState(false);
  const pool=catalog.pools.find(p=>p.id===selected),ids=catalog.restaurants.filter(r=>r.selected).map(r=>r.id);
  const available=pool?.restaurant_ids.filter(id=>catalog.restaurants.some(r=>r.id===id))||[];
  function open(value:RestaurantPool|'new') {if(attempt.current){setEditing(pendingEditor.current);setName(String(attempt.current.name));return;}pendingEditor.current=value;setEditing(value);setName(value==='new'?'':value.name);setError('');attempt.current=null;setRetry(false);requestId.current=crypto.randomUUID();}
  async function mutate(body:Record<string,unknown>){const response=await gameFetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const value=await response.json() as Catalog & {error?:string};if(!response.ok){if(response.status<500){attempt.current=null;setRetry(false);}throw new Error(value.error||'暂时无法保存。');}saved(value);return value;}
  return <div className="restaurant-pools"><div className="pool-heading"><strong>我的常用餐馆池</strong><span>保存后下次直接使用</span></div><div className="pool-toolbar">
    <Select value={pool?.id||''} onValueChange={setSelected} disabled={disabled||busy||!catalog.pools.length}><SelectTrigger aria-label="选择常用餐馆池"><SelectValue placeholder={catalog.pools.length?'选择餐馆池':'还没有保存的餐馆池'}/></SelectTrigger><SelectContent>{catalog.pools.map(p=><SelectItem key={p.id} value={p.id}>{p.name} · {p.restaurant_ids.length} 家</SelectItem>)}</SelectContent></Select>
    <Button variant="outline" disabled={disabled||busy||!pool||available.length<2} onClick={()=>{apply(available);setNotice(`已应用「${pool?.name}」，选中 ${available.length} 家${available.length!==pool?.restaurant_ids.length?'；已跳过被删除的餐馆':''}。`);}}>使用这组</Button>
    <Button variant="outline" disabled={disabled||busy||ids.length<2} onClick={()=>open('new')}>保存当前选择</Button>
  </div>{pool&&<div className="pool-details"><span>{pool.name} · 当前可用 {available.length} 家</span><Button variant="ghost" disabled={disabled||busy||ids.length<2} onClick={()=>open(pool)}>更新这组</Button><Button variant="ghost" disabled={disabled||busy} onClick={()=>{setError('');setDeleting(pool);}}>删除</Button></div>}{notice&&<p role="status" className="pool-notice">{notice}</p>}
    <Dialog open={!!editing} onOpenChange={open=>!open&&!busy&&setEditing(null)}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{editing==='new'?'保存常用餐馆池':'更新常用餐馆池'}</DialogTitle><DialogDescription>保存当前勾选的 {ids.length} 家餐馆。只影响自己的餐馆池，不改动任何饭局。</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{if(!attempt.current)attempt.current={action:'savePool',name,restaurantIds:ids,...(editing==='new'?{requestId:requestId.current}:{id:editing?.id,expectedRevision:editing?.revision})};setRetry(true);const value=await mutate(attempt.current);setSelected(editing==='new'?value.pools.find(p=>!catalog.pools.some(old=>old.id===p.id))?.id||selected:editing?.id||selected);attempt.current=null;setRetry(false);setEditing(null);setNotice('餐馆池已保存。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="field">餐馆池名称<Input required maxLength={40} readOnly={retry} value={name} onChange={e=>setName(e.target.value)} placeholder="例如：工作日午饭"/></label>{retry&&<p className="fine-print">正在确认保存结果，重试会使用同一份名单。</p>}{error&&<p className="error" role="alert">{error}</p>}<Button className="primary full" disabled={busy}>{busy?'正在保存…':retry?'重试保存':'保存餐馆池'}</Button></form></DialogContent></Dialog>
    <AlertDialog open={!!deleting} onOpenChange={open=>!open&&!busy&&setDeleting(null)}><AlertDialogContent className="editor-dialog"><AlertDialogHeader><AlertDialogTitle>删除「{deleting?.name}」？</AlertDialogTitle><AlertDialogDescription>只移除这个常用组合，餐馆和已创建的饭局都会保留。</AlertDialogDescription></AlertDialogHeader>{error&&<p className="error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(!deleting||busy)return;setBusy(true);setError('');try{await mutate({action:'deletePool',id:deleting.id,expectedRevision:deleting.revision});setDeleting(null);setNotice('已删除餐馆池。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
